name: Build and Deploy

on:
  push:
    branches:
      - main  # ou toute autre branche que vous souhaitez surveiller

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 'stable'

    - name: Get Dependencies
      run: flutter pub get

    - name: Build APK
      run: flutter build apk

    - name: Upload APK artifact
      uses: actions/upload-artifact@v2
      with:
        name: app-release
        path: build/app/outputs/flutter-apk/app-release.apk

    - name: Update README
      run: |
        echo "Download the latest release [here](https://hacker-chat-bo.web.app/)" > README.md
      if: always()  # Toujours mettre à jour le README même en cas d'échec
