name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.13.9'

    - name: Get Dependencies
      run: flutter pub get

    - name: Build APK
      run: flutter build apk

    - name: Create Last Release Directory
      run: mkdir -p last-release

    - name: Move APK to Last Release Directory
      run: mv build/app/outputs/flutter-apk/app-release.apk ./last-release

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v2
      with:
        name: app-release
        path: ./last-release/app-release.apk
